name: black-action
on: push
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Commit lint changes
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          # add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: ":art: Format Python code with psf/black"
          # force: false
          # target_branch: update/version # to create a new branch
